	CREATE DATABASE IF NOT EXISTS UPOINT_PRODUCT;
	
	USE UPOINT_PRODUCT;
	
	CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY(
		CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY, 
		CATEGORY_NAME VARCHAR(25) NOT NULL,
		CATEGORY_DESCRIPTION VARCHAR(300) NULL,
		PARENT_CATEGORY_ID INT,
		FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(CATEGORY_ID)
	);