CREATE DATABASE IF NOT EXISTS UPOINT_USER;

USE UPOINT_USER;

CREATE TABLE IF NOT EXISTS USER_LOGIN(
	USER_LOGIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	LOGIN_EMAIL VARCHAR(20) NOT NULL,
	LOGIN_PW VARCHAR(15) NOT NULL
	);

CREATE TABLE IF NOT EXISTS USER_ROLE(
	USER_ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	ROLE_NAME VARCHAR(30) NOT NULL,
	ROLE_WRITE_ACCES BIT NOT NULL,
	ROLE_READ_ACCES BIT NOT NULL,
	ROLE_MODIFY_ACCES BIT NOT NULL,
	ROLE_DELETE_ACCES BIT NOT NULL
	);

CREATE TABLE IF NOT EXISTS USER_(
	USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	USER_ROLE_ID BIGINT NOT NULL,
	USER_LOGIN_ID BIGINT NOT NULL,
	FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLE (USER_ROLE_ID),
	FOREIGN KEY (USER_LOGIN_ID) REFERENCES USER_LOGIN (USER_LOGIN_ID)
	);
	