CREATE DATABASE IF NOT EXISTS UPOINT_USER;

USE UPOINT_USER;

CREATE TABLE IF NOT EXISTS USER_LOGIN(
USER_LOGIN_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_EMAIL VARCHAR(12) NOT NULL,
USER_PASSWORD VARCHAR(16) NOT NULL);

CREATE TABLE IF NOT EXISTS USER_ROLE(
USER_ROLE_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ROLE_NAME VARCHAR(14) NOT NULL,
ROLE_WRITE_RECEIVING_ORDER_ACCESS BIT NOT NULL ,
ROLE_READ_RECEIVING_ORDER_ACCESS BIT NOT NULL);

CREATE TABLE IF NOT EXISTS USER_(
USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
USER_LOGIN_ID BIGINT NOT NULL,
USER_ROLE_ID BIGINT NOT NULL,
FOREIGN KEY (USER_ROLE_ID) REFERENCES USER_ROLE(USER_ROLE_ID),
FOREIGN KEY (USER_LOGIN_ID) REFERENCES USER_LOGIN(USER_LOGIN_ID)
);