	CREATE DATABASE IF NOT EXISTS UPOINT_PRODUCT;
	
	USE UPOINT_PRODUCT;
	
	CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY(
		CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY, 
		CATEGORY_NAME VARCHAR(25) NOT NULL,
		CATEGORY_DESCRIPTION VARCHAR(300) NULL,
		PARENT_CATEGORY_ID INT,
		FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(CATEGORY_ID)
	);
	
	CREATE TABLE IF NOT EXISTS PRODUCT(
		PRODUCT_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		PRODUCT_CODE VARCHAR(16) NOT NULL,
		PRODUCT_NAME VARCHAR(25) NOT NULL,
		PRODUCT_DESCRIPTION VARCHAR(250) NULL,
		PRODUCT_CATEGORY_ID INT NOT NULL,
		PRODUCT_COMPANY_ID BIGINT NOT NULL,
		FOREIGN KEY (PRODUCT_CATEGORY_ID) REFERENCES PRODUCT_CATEGORY(CATEGORY_ID)
	);
	
	CREATE TABLE IF NOT EXISTS PRODUCT_PROPERTY(
		PROPERTY_ID INT AUTO_INCREMENT PRIMARY KEY,
		PROPERTY_NAME VARCHAR(15) NOT NULL,
		PROPERTY_UNIT VARCHAR(10) NOT NULL,
		PROPERTY_TYPE VARCHAR(10) NOT NULL
	);
	
	CREATE TABLE IF NOT EXISTS PRODUCT_PROPERTY_ASSOCIATION(
		PRODUCT_PROPERTY_ASSOCIATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
		PRODUCT_ID BIGINT NOT NULL,
		PROPERTY_ID INT NOT NULL,
		FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID),
		FOREIGN KEY (PROPERTY_ID) REFERENCES PRODUCT_PROPERTY(PROPERTY_ID)
	);
	
	CREATE TABLE IF NOT EXISTS PROPERTY_AVAILABLE_UNIT(
		PROPERTY_AVAILABLE_UNIT_ID INT NOT NULL PRIMARY KEY,
		AVAILABLE_UNIT VARCHAR(10) NOT NULL,
		FOREIGN KEY (PROPERTY_AVAILABLE_UNIT_ID) REFERENCES PRODUCT_PROPERTY(PROPERTY_ID)
	);
	
	
	
	